### PR TITLE
Fix batch file execution

### PR DESCRIPTION
**Pull request by Nikita240**
So I would get an error whenever I tried placing any latex. I figured out that manually executing the created batch files correctly creates the .pdf's. 

After attaching the debbugger I pretty much traced it down to the system() call not behaving correctly. It conveniently had a TODO comment and a commented out method call. Swapping the comment blocks around fixed my problem :)

### CODE REVIEW

**Comment by stoani89** [comment]
Thanks for contributing!

The reason the batch file is executed the way it is, is that with the `system` call a console opens which gives a visual feedback to the user that something (either `latex` or `ghostscript`) is being executed. With the `L2A::UTIL::ExecuteCommandLine` everything runs in the background and it feels like Illustrator is frozen. I would like to keep it that way, one possible extension could be to add a sort of "progress feedback" to the LaTeX2AI forms.

What is the issue you have with your `system` call, why doesn't it work? Could you post the error message and the Versions of Windows / Illustrator / VisualStudio / LaTeX / ghostscript you are using.

**Comment by Nikita240** [comment]
There was no meaningful error message. 

I honestly can't make sense of it. Take a look at what the debugger shows:

image

It seems like the `system()` call is just straight up not working. If I just double click the `batch` file myself while in the debugger, you can see it generates the `.pdf` correctly.

image

Illustrator 2021
pdfTeX, Version 3.14159265-2.6-1.40.21 (MiKTeX 20.12)
VisualStudio 2019 (but I have the 2017 SDK and I'm building with the toolset that's in the project file)
GhostScript 9.53.3

**Comment by Nikita240** [comment]
Ahhhhhhhhhh it's the thousand year "whitespace in the filename" problem.

I pushed the fix.

**Comment by stoani89** [comment]
A classic one ;) good catch.

I am OK  with merging this. Since this can be a fatal bug I added a test in the branch `add-whitepace-test`. Please merge those changes into your feature branch (then the test should pass).

I also added a contributing section to the readme, please have a quick look.

**Comment by stoani89** [comment]
@Nikita240 I added some tests and documentation to your changes and started a pull request (see #32). If you want to be included in the `CONTRIBUTORS` file please add yourself and open a pull request to the feature branch (`add-whitespace-test`). I will merge this in the next couple of days since this bug already affects some people.

**Comment by Nikita240** [comment]
@stoani89 done.

Sorry for the delay, I should have completed the feature branch myself. Just got caught up doing a release at work.

Thank you for accepting my contribution.

**Comment by stoani89** [comment]
No worries, thank you for finding the bug.

**Pull request closed without merging**
